name: cd

on:
  push:
    tags:
      - "v**"

jobs:
  aws:
    name: AWS
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials using Secrets
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO: fragments
          VERSION_TAG: ${{ github.ref_name }}
        uses: docker/build-push-action@v6
        with:
          context: ./fragments-backend
          file: ./fragments-backend/Dockerfile
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}:${{ env.VERSION_TAG }}, ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}:latest

      - name: Update ECS task definition with new image
        run: |
          # Get the ECR image URI
          ECR_IMAGE="${{ steps.login-ecr.outputs.registry }}/fragments:${{ github.ref_name }}"
          
          # Update the task definition file with the new image
          sed -i "s|image:.*|image: \"$ECR_IMAGE\"|" fragments-backend/ecs-task-definition.json
          
          # Register the new task definition
          echo "Registering task definition with image: $ECR_IMAGE"
          aws ecs register-task-definition --cli-input-json file://fragments-backend/ecs-task-definition.json

      - name: Check and create ECS cluster if needed
        run: |
          # Check if cluster exists
          if ! aws ecs describe-clusters --clusters fragments --query 'clusters[0].status' --output text 2>/dev/null | grep -q ACTIVE; then
            echo "Creating ECS cluster 'fragments'..."
            aws ecs create-cluster --cluster-name fragments
          else
            echo "ECS cluster 'fragments' already exists"
          fi

      - name: Check and create ECS service if needed
        run: |
          # Check if service exists
          if ! aws ecs describe-services --cluster fragments --services fragments --query 'services[0].status' --output text 2>/dev/null | grep -q ACTIVE; then
            echo "Creating ECS service 'fragments'..."
            
            # Get the latest task definition ARN
            TASK_DEF_ARN=$(aws ecs describe-task-definition \
              --task-definition fragments:${{ github.ref_name }} \
              --query 'taskDefinition.taskDefinitionArn' \
              --output text)
            
            echo "Using task definition: $TASK_DEF_ARN"
            
            # Create service with default network configuration
            aws ecs create-service \
              --cluster fragments \
              --service-name fragments \
              --task-definition $TASK_DEF_ARN \
              --desired-count 1 \
              --launch-type FARGATE \
              --network-configuration "awsvpcConfiguration={subnets=[subnet-12345678],securityGroups=[sg-12345678],assignPublicIp=ENABLED}" \
              || echo "Service creation failed - will try to update existing service"
          else
            echo "ECS service 'fragments' already exists"
          fi

      - name: Update ECS service
        run: |
          echo "Updating ECS service with new task definition..."
          aws ecs update-service \
            --cluster fragments \
            --service fragments \
            --task-definition fragments:${{ github.ref_name }}

      - name: Wait for service stability
        run: |
          echo "Waiting for service to become stable..."
          aws ecs wait services-stable \
            --cluster fragments \
            --services fragments
