name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: npm ci
        working-directory: fragments-backend
      - run: npm run lint
        working-directory: fragments-backend

  dockerfile-lint:
    name: Dockerfile Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: fragments-backend/Dockerfile

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: npm ci
        working-directory: fragments-backend
      - name: Run Unit Tests
        run: npm test
        working-directory: fragments-backend
        env:
          PORT: 8080
          LOG_LEVEL: silent
          HTPASSWD_FILE: tests/.htpasswd

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Install node dependencies
        working-directory: fragments-backend
        # NOTE: we need to install dev dependencies too vs. production only for hurl
        run: npm install
      - name: Build Containers
        working-directory: fragments-backend
        run: docker compose -f docker-compose.yml up -d
      - name: Setup Local AWS Resources
        working-directory: fragments-backend
        run: chmod +x ./scripts/local-aws-setup.sh && ./scripts/local-aws-setup.sh
      - name: Wait for server to be ready
        working-directory: fragments-backend
        run: |
          echo "Waiting for server to start..."
          sleep 10
          echo "Checking if server is responding..."
          curl -f http://localhost:8080/health || exit 1
      - name: Run Hurl Tests
        working-directory: fragments-backend
        run: npm run test:integration

  docker-hub:
    name: Build and Push to Docker Hub
    needs: [lint, dockerfile-lint, unit-tests, integration-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./fragments-backend
          file: ./fragments-backend/Dockerfile
          push: true
          tags: |
            kdewasi/fragments:sha-${{ github.sha }}
            kdewasi/fragments:main
            kdewasi/fragments:latest
